싱글톤 제거 레벨업
tttghost/wheelmaker pull request #61
Opened 2024-11-20 12:22 UTC by tttghost

기존 코드들의 성격을 다시 차근히 보다보니 슈퍼울트라 싱글톤 의존도가 있어
그냥 다 주석하고 하나씩 기능을 살리는 쪽으로 해 보겠습니다.

레벨업 시 PlayerLevel의 변수 값이 1 증가 되는 코드 작성

2024-11-20 13:50 UTC, tttghost commented
작성주신 싱글톤 변환 코드를 늦게나마 살펴보며 생각 후 코드작업을 해 봤습니다,,

오후 7:48 2024-11-20 시작
오후 7:57 2024-11-20 스크립트 열어봄 DTO
오후 7:58 2024-11-20 PR Merge
오후 8:04 2024-11-20 2023.2.19f1설치
오후 8:21 2024-11-20 에디터 설치완료 실행해보며 분석 어셈블리는 뭔가요? WheelMaker.Common, WheelMaker.Manager.Level...
오후 9:25 2024-11-20 한단계 코드 수정...
오후 9:28 2024-11-20 두가지 부분에 대해 수정을 주셨는데 DB쪽과 Levelup쪽 인듯 해 보였는데 DB쪽 수정은 없었던 것 같아 보입니다.
오후 9:35 2024-11-20 ILevel의 Up이 속성에 따라 오르는 것이 아닌 (wheel,click,auto) 이라고 적다가 다시 보니 제가 잘못 봤습니다.
오후 9:50 2024-11-20 어셈블리 만드는 방법? 하는 이유? 적으면 싱글톤을 호출 못 하더라구요.
IGoods interface는 상품을 뜻하며 그 속성으로 골드 값을 가지고 있음
int type의 양만큼 Gold를 추가/삭제 해서 현재 Gold의 양을 나타낼 수 있음
이라고 하는데 그럼 상품의 골드가치와
내 골드 양 까지 이 인터페이스 하나로 되는 것인가요??
오후 9:54 2024-11-20
interface IRequiredLevel
{
    int ByBehaviours(Behaviours behaviour);
} 이부분만으로는 각 상품별 필요골드량을 알아 낼 수 있나요?
오후 10:30 2024-11-20 이넘값이 마우스휠로 되어있어서 헷갈림, 그냥 휠 임
오후 10:49 2024-11-20 싱글톤 제거 레벨업 PR

2024-11-21 07:59 UTC, jongfeel requested changes
이 코드들은 정의한 대로 구현만 했을 뿐
리뷰나 협의 과정이 없었으므로 merge가 되면 안됩니다.

따라서 Close 하는 게 좋겠습니다.

2024-11-21 07:59 UTC, jongfeel commented on Assets/_Dev/Scripts/Manager/Interfaces/IGoods.cs
> +namespace WheelMaker.Manager.Interfaces // 인터페이스의 습관화!!
이런 주석은 안 넣는게 좋습니다.
```suggestion
namespace WheelMaker.Manager.Interfaces
```

2024-11-21 07:59 UTC, jongfeel commented on Assets/_Dev/Scripts/Manager/Level/PlayerLevel.cs
> +    }
데이터 중심의 클래스는 객체지향적 설계에서는 필요 없습니다.

2024-11-21 07:59 UTC, jongfeel commented on Assets/_Dev/Scripts/Manager/Level/PlayerLevel.cs
> +    public class PlayerLevel : MonoBehaviour, ILevel, IRequiredLevel
두 인터페이스가 한 class에 구현되어야 한다는 가정은 하지 않았고, 협의도 하지 않았습니다.
그러므로 이 코드는 merge가 되면 안됩니다.

2024-12-04 02:16 UTC, tttghost commented on Assets/_Dev/Scripts/Manager/Interfaces/IGoods.cs
> +namespace WheelMaker.Manager.Interfaces // 인터페이스의 습관화!!
네엡!

2024-12-04 15:40 UTC, closed without merging